### ISSUE TITLE
normalize the number as a preprocessing step

### ISSUE THREAD

**Issue by Deaddawn** [PolymathicAI/xVal#4]
Hi, there. As mentioned in your paper, "**we normalize numbers in the text corpus such that they fall within the range [−5, 5] as a preprocessing step before training**". 

Wondering where exactly the code is? Haven't seen it in preprocess.py.

**Comment by golkar** [comment]
This preprocessing step is done on a per-dataset basis and can for example be seen in [here](https://github.com/PolymathicAI/xVal/blob/653a9424280e107817ac2d75079ca38b529b3c52/planets-sim/draw_sample.py#L17) in the case of the planet sim. Because you might want to rescale the different parts of your sample differently (for example, in the planets dataset, we rescale the masses and the eccentricities separately), it is something that needs thought on a per-dataset basis.
